### ISSUE TITLE
docs: Setup step missing?

### ISSUE THREAD

**Issue by saschwarz** [danielroe/nuxt-ionic#10]
### 📚 Is your documentation request related to a problem?

I created a new project via:
```
npx nuxi init -t v3 audio-flashcards-nuxt
cd audio-flashcards-nuxt
yarn add --dev nuxt-ionic
```
I edited `nuxt.config.ts` to:
```
import { defineNuxtConfig } from "nuxt";

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  modules: ["nuxt-ionic"],
});
```

When I run `yarn run dev` the console shows:
```
yarn run v1.22.18
$ nuxt dev

Nuxt CLI v3.0.0-rc.4                                                                                                                                                         06:26:41
                                                                                                                                                                             06:26:41
  > Local:    http://localhost:3001/ 


 WARN  [PWA] Icon not found at /Users/saschwarz/dev/audio-flashcards-nuxt/public/icon.png                                                                                    06:26:44

ℹ Vite client warmed up in 748ms                                                                                                                                             06:26:46
ℹ Vite server warmed up in 123ms                                                                                                                                             06:26:46
✔ Vite server built in 1632ms                                                                                                                                                06:26:47
✔ Nitro built in 358 ms                                                                                                                                                nitro 06:26:48
[nuxt] [request error] Cannot read properties of undefined (reading 'forEach')
  at createRouterMatcher (./node_modules/vue-router/dist/vue-router.cjs.js:1485:12)  
  at Module.createRouter (./node_modules/vue-router/dist/vue-router.cjs.js:2819:21)  
  at Module.createRouter (./.nuxt/dist/server/server.mjs:3468:42)  
  at ./.nuxt/dist/server/server.mjs:2487:40  
  at fn (./.nuxt/dist/server/server.mjs:380:27)  
  at Object.callAsync (./node_modules/unctx/dist/index.mjs:41:19)  
  at callWithNuxt (./.nuxt/dist/server/server.mjs:382:23)  
  at applyPlugin (./.nuxt/dist/server/server.mjs:337:29)  
  at Module.applyPlugins (./.nuxt/dist/server/server.mjs:347:11)  
  at async createNuxtAppServer (./.nuxt/dist/server/server.mjs:46:7)
[nuxt] [request error] Cannot read properties of undefined (reading 'forEach')
  at createRouterMatcher (./node_modules/vue-router/dist/vue-router.cjs.js:1485:12)  
  at Module.createRouter (./node_modules/vue-router/dist/vue-router.cjs.js:2819:21)  
  at Module.createRouter (./.nuxt/dist/server/server.mjs:3468:42)  
  at ./.nuxt/dist/server/server.mjs:2487:40  
  at fn (./.nuxt/dist/server/server.mjs:380:27)  
  at Object.callAsync (./node_modules/unctx/dist/index.mjs:41:19)  
  at callWithNuxt (./.nuxt/dist/server/server.mjs:382:23)  
  at applyPlugin (./.nuxt/dist/server/server.mjs:337:29)  
  at Module.applyPlugins (./.nuxt/dist/server/server.mjs:347:11)  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

If I paste the default ionic settings into `nuxt.config.ts` and disable `router` the error disappears.

**Comment by danielroe** [comment]
Do you have any files in your `pages/` directory?

**Comment by saschwarz** [comment]
Not yet. I only did the steps outlined above, so the project only contains the output of the default vue3 nuxt template. I wanted to see if the index page would render to confirm everything worked.

**Comment by danielroe** [comment]
Understood.
