### ISSUE TITLE
Cannot start nuxt issue when trying to start playground 

### ISSUE THREAD

**Issue by Lexpeartha** [danielroe/nuxt-ionic#20]
### 📚 What are you trying to do?

After following the steps in the project's README, I ran `pnpm dev` and got the following error:
```
 ERROR  Cannot start nuxt:  Cannot find module '/home/aleksa/Desktop/Projects/nuxt-ionic/dist/module.cjs'

  at createEsmNotFoundErr (node:internal/modules/cjs/loader:954:15)
  at finalizeEsmResolution (node:internal/modules/cjs/loader:947:15)
  at trySelf (node:internal/modules/cjs/loader:458:12)
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:910:24)
  at Function.resolve (node:internal/modules/cjs/helpers:108:19)
  at Function._resolve [as resolve] (node_modules/.pnpm/jiti@1.14.0/node_modules/jiti/dist/jiti.js:1:108226)
  at resolveModule (node_modules/.pnpm/@nuxt+kit@3.0.0-rc.4/node_modules/@nuxt/kit/dist/index.mjs:242:29)
  at normalizeModule (node_modules/.pnpm/@nuxt+kit@3.0.0-rc.4/node_modules/@nuxt/kit/dist/index.mjs:412:18)
  at installModule (node_modules/.pnpm/@nuxt+kit@3.0.0-rc.4/node_modules/@nuxt/kit/dist/index.mjs:397:47)
  at initNuxt (node_modules/.pnpm/nuxt@3.0.0-rc.4/node_modules/nuxt/dist/index.mjs:1334:13)
```

### 🔍 What have you tried?

I tried deleting lock file and `node_modules` and installing deps again, but even after reinstalling I get the same error

**Comment by danielroe** [comment]
Ah, you're trying to develop the module? I think you might need to run `pnpm dev:prepare`. A PR would be welcomed if so 😊

**Comment by Lexpeartha** [comment]
Running `pnpm dev:prepare` before `pnpm dev` fixed it 👍🏽
