### ISSUE TITLE
help: 

### ISSUE THREAD

**Issue by JanHuyBE** [danielroe/nuxt-ionic#33]
### 📚 What are you trying to do?

Since 11/08/2022 the nuxt-ionic does not work anymore. (the days before I could start projects without problems)
Has today's nuxt RC7 something to do with it? Is saw that nuxt and nuxt/kit have a different version number in the repo.  
A standard nuxt installation RC7 and a antfu/vitesse-nuxt3 RC6 are working without problems.
   
ON MY LOCAL PC as well as on the PLAYGROUND I get quasi similar Error message. 

'FROM THE PLAYGROUND'

ℹ Vite server warmed up in 1407ms                                                                                 18:51:56
✔ Vite server built in 3783ms                                                                                     18:52:00
✔ Nitro built in 352 ms                                                                                     nitro 18:52:00
Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/home/projects/yqnikongn.github/node_modules/@stencil/core/internal/app-data' is not supported resolving ES modules imported from /home/projects/yqnikongn.github/.nuxt/dist/server/server.mjs
Did you mean to import @stencil/core/internal/app-data/index.cjs?
    at InternalError.get (https://yqnikongn--github.w.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:292488)
    at defaultResolve (https://yqnikongn--github.w.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:622935)
    at ESMLoader.resolve (https://yqnikongn--github.w.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:1210848)
    at ESMLoader.getModuleJob (https://yqnikongn--github.w.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:1208564)
    at ESMLoader.import (https://yqnikongn--github.w.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:1208951)
    at importModuleDynamically (https://yqnikongn--github.w.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:981760)
    at i.importModuleDynamicallyCallback (https://yqnikongn--github.w.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:246238)
    at _0x69e4ca (https://yqnikongn--github.w.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:15:291665)
    at $id_0LwZducjkC (file:///home/projects/yqnikongn.github/.nuxt/dist/server/server.mjs:10145:1)
    at __instantiateModule__ (file:///home/projects/yqnikongn.github/.nuxt/dist/server/server.mjs:53841:9)
    at __ssrLoadModule__ (file:///home/projects/yqnikongn.github/.nuxt/dist/server/server.mjs:53779:25)
    at ssrImport (file:///home/projects/yqnikongn.github/.nuxt/dist/server/server.mjs:53804:13)
    at $id_PKJWOgL73L (file:///home/projects/yqnikongn.github/.nuxt/dist/server/server.mjs:7021:37)
    at __instantiateModule__ (file:///home/projects/yqnikongn.github/.nuxt/dist/server/server.mjs:53841:9)
    at __ssrLoadModule__ (file:///home/projects/yqnikongn.github/.nuxt/dist/server/server.mjs:53779:25)
    at ssrImport (file:///home/projects/yqnikongn.github/.nuxt/dist/server/server.mjs:53804:13)
    at $id_6lIMJNrk8A (file:///home/projects/yqnikongn.github/.nuxt/dist/server/server.mjs:6526:37)
    at __instantiateModule__ (file:///home/projects/yqnikongn.github/.nuxt/dist/server/server.mjs:53841:9)
    at __ssrLoadModule__ (file:///home/projects/yqnikongn.github/.nuxt/dist/server/server.mjs:53779:25)
    at ssrImport (file:///home/projects/yqnikongn.github/.nuxt/dist/server/server.mjs:53804:13)
    at $id_6sf4FcQw81 (file:///home/projects/yqnikongn.github/.nuxt/dist/server/server.mjs:4249:37)
    at async __instantiateModule__ (file:///home/projects/yqnikongn.github/.nuxt/dist/server/server.mjs:53841:3) {
  code: 'ERR_UNSUPPORTED_DIR_IMPORT',
  url: 'file:///home/projects/yqnikongn.github/node_modules/@stencil/core/internal/app-data'
}
[nuxt] [request error] [unhandled] [500] [vite dev] Error loading external "@stencil/core/internal/app-data".
  at async eval (./.nuxt/dev/index.mjs:117:22)  
  at async eval (./node_modules/h3/dist/index.mjs:571:19)  
  at async Server.nodeHandler (./node_modules/h3/dist/index.mjs:517:7)
ℹ Vite client warmed up in 12074ms

**Comment by danielroe** [comment]
This should be resolved in v0.3.1.

**Comment by JanHuyBE** [comment]
I could not test the new version due to Corona. But thanks for the solution.

Met vriendelijke groeten,

Jan Huybrecht
Isidoor Van Kerrebroeckstraat 14    |    9810 Eke    |    Belgium
+32 473 78 13 32    |    +32 9 245 47 67    |    ***@***.***


Op ma 15 aug. 2022 om 11:56 schreef Daniel Roe ***@***.***>:
